### PR TITLE
Jls stripes2

### PR DESCRIPTION
**Pull request by jlsilva1994**
take a look on this version of hero section. Some changes in other parts of the site, like changing main colors and colors of buttons.

### CODE REVIEW

**Comment by fntneves** [comment]
First of all, please remove .DS_store and bundle files from this PR.
Namely, `public/css` and `public/js` folders.
I will take a look, soon.

**Comment by fntneves** [comment]
The hero section is a little bit small. I think we need more space for that section, to include our small intro. Moreover, the colors are a bit extreme, compared to what I was expecting.

I will give you an example of what I was expecting (not strictly equal, but more similar).
screen shot 2017-03-08 at 09 28 54

**Review by fntneves — CHANGES_REQUESTED** [review]
The hero section is a little bit small. I think we need more space for that section, to include our small intro. Moreover, the colors are a bit extreme, compared to what I was expecting.

I will give you an example of what I was expecting (not strictly equal, but more similar).
screen shot 2017-03-08 at 09 28 54

**Comment by jlsilva1994** [comment]
The Changes you requested were committed some time ago, I ask you to check them and give a feedback on the updated version

**Comment by fntneves** [comment]
test

**Comment by fntneves** [comment]
test

**Pull request closed without merging**
